Repository MiguelPerezMartinez/apollofy-music-project, pull requests merged in 2021-10, with the labels that each got.

#113 Profile default image --> Done
  client/public/assets/img/default-user.svg
  client/public/assets/img/eddy-lackmann-lLdGG3ESoiI-unsplash.jpg
  client/src/components/ProfileCircleIcon/ProfileCircleIcon.js
  client/src/components/ProfileCircleIcon/styles.css
  client/src/index.css
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/styles.css
  client/src/services/api/fileUploader.js
  client/src/services/api/index.js
  server/src/controllers/userController.js
  server/src/models/userModel.js
Labels: must-have, user-story, feat

#114 Fb/fix right menu upload track profile img
  client/package-lock.json
  client/package.json
  client/public/assets/img/eddy-lackmann-lLdGG3ESoiI-unsplash.jpg
  client/src/App.js
  client/src/App.test.js
  client/src/components/ModalTrackUp/ModalTrackUp.js
  client/src/components/ModalTrackUp/styles.css
  client/src/components/ProfileCircleIcon/ProfileCircleIcon.js
  client/src/components/ProfileCircleIcon/styles.css
  client/src/components/RightMenu/RightMenu.js
  client/src/hoc/BarsAndModal.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/pages/Home/Home.js
  client/src/pages/Profile/Profile.js
  client/src/redux/userData/state.js
  client/src/reportWebVitals.js
  client/src/services/api/trackUpload.js
Labels: user-story, fix

#118 F/#83 play bar
  client/package-lock.json
  client/package.json
  client/src/components/BlockTrack/BlockTrack.js
  client/src/components/PlayBar/PlayBar.js
  client/src/components/PlayBar/index.js
  client/src/components/PlayBar/styles.css
  client/src/components/PlayButton/PlayButton.js
  client/src/components/PlayButton/index.js
  client/src/components/Track/Track.js
  client/src/components/WaveSound/WaveSound.js
  client/src/components/WaveSound/index.js
  client/src/components/WaveSound/style.css
  client/src/pages/Home/Home.js
  client/src/pages/Home/sound.wav
  client/src/pages/Home/sound2.wav
  client/src/pages/Home/style.css
  client/src/redux/trackData/actions.js
  client/src/redux/trackData/reducer.js
  client/src/redux/trackData/state.js
  client/src/redux/trackData/type.js
Labels: must-have, user-story, feat

#116 B/liked by id endpoint
  client/.gitignore
  client/package-lock.json
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/styles.css
  client/src/index.css
  server/src/controllers/trackController.js
  server/src/routes/trackRoutes.js
Labels: must-have, feat

#119 F/home grid
  client/package-lock.json
  client/package.json
  client/src/components/BlockTrack/BlockTrack.js
  client/src/components/BlockTrack/styles.css
  client/src/components/Track/Track.js
  client/src/components/Track/styles.css
  client/src/components/TrackBox/TrackBox.js
  client/src/components/TrackBox/index.js
  client/src/components/TrackBox/styles.css
  client/src/components/TrackImg/TrackImg.js
  client/src/components/TrackImg/index.js
  client/src/components/TrackImg/styles.css
  client/src/index.css
  client/src/pages/Home/Home.js
  server/package-lock.json
Labels: feat

#120 F/elements list page
  client/src/App.js
  client/src/components/RightMenu/RightMenu.js
  client/src/components/TrackBox/TrackBox.js
  client/src/components/TrackBox/index.js
  client/src/components/TrackBox/styles.css
  client/src/components/TrackImg/TrackImg.js
  client/src/pages/ElementsList/ElementsList.js
  client/src/pages/ElementsList/index.js
  client/src/pages/Home/Home.js
  client/src/pages/Home/sound.wav
  client/src/pages/Home/sound2.wav
  client/src/pages/Profile/Profile.js
  client/src/redux/isAuthorized/actions.js
  client/src/redux/isAuthorized/reducer.js
  client/src/redux/isAuthorized/types.js
  client/src/redux/userData/actions.js
  client/src/redux/userData/reducer.js
  client/src/redux/userData/state.js
  client/src/redux/userData/types.js
  client/src/services/api/apiAuth.js
  server/src/apollofy-music-project-firebase-adminsdk-eub4j-a33eeadcc7.json
  server/src/controllers/userController.js
  server/src/routes/userRoutes.js
Labels: feat

#121 F/home elements
  client/src/components/BlockTrack/BlockTrack.js
  client/src/components/BlockTrack/styles.css
  client/src/components/Track/Track.js
  client/src/components/Track/styles.css
  client/src/components/TrackImg/TrackImg.js
  client/src/components/TrackImg/play-button-hover.svg
  client/src/components/TrackImg/styles.css
  client/src/index.css
  client/src/pages/Home/Home.js
  client/src/pages/Home/style.css
  client/src/pages/Home/styles.css
  client/src/services/api/apiAuth.js
  client/src/services/api/index.js
Labels: feat

#122 F/playbar menu mergeall
  client/.gitignore
  client/public/assets/img/apollofy-music-project-firebase-adminsdk-eub4j-a33eeadcc7.json
  client/src/components/BlockTrack/styles.css
  client/src/components/BottomMenu/BottomMenu.js
  client/src/components/BottomMenu/index.js
  client/src/components/BottomMenu/styles.css
  client/src/components/DialogBox/styles.css
  client/src/components/ModalTrackUp/ModalTrackUp.js
  client/src/components/PlayBar/PlayBar.js
  client/src/components/PlayBar/styles.css
  client/src/components/ProfileCircleIcon/styles.css
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/styles.css
  client/src/components/Track/Track.js
  client/src/components/Track/styles.css
  client/src/components/TrackImg/styles.css
  client/src/hoc/BarsAndModal.js
  client/src/index.css
  client/src/pages/Home/Home.js
  client/src/redux/trackData/actions.js
  server/src/middlewares/authMiddleware.js
  server/src/routes/trackRoutes.js
Labels: fix

#123 B/several endpoints
  server/src/controllers/trackController.js
  server/src/controllers/userController.js
  server/src/models/trackModel.js
  server/src/models/userModel.js
  server/src/routes/trackRoutes.js
  server/src/routes/userRoutes.js
Labels: feat

#124 F/queue history played
  client/src/components/BlockTrack/BlockTrack.js
  client/src/components/PlayBar/PlayBar.js
  client/src/components/Track/Track.js
  client/src/pages/Home/Home.js
  client/src/redux/trackData/actions.js
  client/src/redux/trackData/reducer.js
  client/src/redux/trackData/state.js
  client/src/redux/trackData/type.js
  package-lock.json
Labels: must-have, feat

#132 F/rendering home track categories
  client/package-lock.json
  client/src/components/PlayBar/PlayBar.js
  client/src/pages/Home/Home.js
  client/src/services/api/apiAuth.js
  client/src/services/api/index.js
  server/src/controllers/trackController.js
Labels: feat, fix

#135 F/like handler
  client/src/components/BlockTrack/BlockTrack.js
  client/src/components/BlockTrack/styles.css
  client/src/components/FavButton/FavButton.js
  client/src/components/FavButton/index.js
  client/src/components/PlayBar/PlayBar.js
  client/src/components/Track/Track.js
  client/src/services/api/apiTrack.js
Labels: feat

#145 B/playlist like management
  server/src/controllers/index.js
  server/src/controllers/playlistController.js
  server/src/controllers/trackController.js
  server/src/models/index.js
  server/src/models/playlistModel.js
  server/src/models/trackModel.js
  server/src/routes/index.js
  server/src/routes/playlistRoutes.js
  server/src/routes/trackRoutes.js
  server/src/server.js
Labels: must-have, feat

#189 Fb/search bar renders
  client/package-lock.json
  client/src/components/DialogueBox/DialogueBox.js
  client/src/components/DialoguePlaylist/DialoguePlaylist.js
  client/src/components/Playlist/Playlist.js
  client/src/components/ShareModal/ShareModal.js
  client/src/pages/ElementsList/ElementsList.js
  client/src/pages/PlaylistView/PlaylistView.js
  client/src/pages/Search/Search.js
  client/src/services/api/apiPlaylist.js
  client/src/services/api/apiTrack.js
  client/src/services/api/index.js
  client/src/services/api/trackManager.js
  server/package-lock.json
  server/src/controllers/playlistController.js
  server/src/routes/playlistRoutes.js
  server/src/routes/userRoutes.js
Labels: must-have
