Repository MiguelPerezMartinez/apollofy-music-project, pull requests merged in 2021-09, with the labels that each got.

#30 Starting point
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  package.json
  server/index.js
  server/package.json
Labels: must-have

#31 B/26
  .prettierrc
  server/.env
  server/index.js
  server/package.json
  server/src/config/config.js
  server/src/config/index.js
  server/src/controllers/index.js
  server/src/db/connect.js
  server/src/db/index.js
  server/src/index.js
  server/src/middlewares/index.js
  server/src/models/index.js
  server/src/routes/index.js
  server/src/server.js
Labels: must-have, feat

#33 F/27
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/ReducerTest/ReducerTest.js
  client/src/components/ReducerTest/index.js
  client/src/index.js
  client/src/pages/Home/Home.js
  client/src/pages/Home/index.js
  client/src/pages/Login/Login.js
  client/src/pages/Login/index.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/index.js
  client/src/pages/Register/Register.js
  client/src/pages/Register/index.js
  client/src/redux/provider.js
  client/src/redux/reducers.js
  client/src/redux/store.js
  client/src/redux/stringTest/action.js
  client/src/redux/stringTest/reducer.js
  client/src/redux/stringTest/state.js
  client/src/redux/stringTest/types.js
Labels: feat

#34 Plantilla Login - feat #F/13
  client/package.json
  client/src/pages/Login/Login.js
  client/src/pages/Login/login.css
Labels: feat

#35 register form implemented without styles feat #5
  client/src/pages/Register/Register.js
Labels: feat

#37 feat #36 : created Input component and added to Login page
  client/src/components/Input/Input.js
  client/src/components/Input/index.js
  client/src/components/Input/styles.css
  client/src/pages/Login/Login.js
  client/src/pages/Register/Register.js
Labels: feat

#40 F/38
  .gitignore
  .prettierrc
  client/.gitignore
  client/README.md
  client/package.json
  client/public/assets/img/home.svg
  client/public/assets/img/logout.svg
  client/public/assets/img/search.svg
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/App.test.js
  client/src/colors.css
  client/src/components/ProfileCircleIcon/ProfileCircleIcon.js
  client/src/components/ProfileCircleIcon/index.js
  client/src/components/ProfileCircleIcon/styles.css
  client/src/components/ReducerTest/ReducerTest.js
  client/src/components/ReducerTest/index.js
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/index.js
  client/src/components/RightMenu/styles.css
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/pages/Home/Home.js
  client/src/pages/Home/index.js
  client/src/pages/Login/Login.js
  client/src/pages/Login/index.js
  client/src/pages/Login/login.css
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/index.js
  client/src/pages/Register/Register.js
  client/src/pages/Register/index.js
  client/src/redux/provider.js
  client/src/redux/reducers.js
  client/src/redux/store.js
  client/src/redux/stringTest/action.js
  client/src/redux/stringTest/reducer.js
  client/src/redux/stringTest/state.js
  client/src/redux/stringTest/types.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  package.json
  server/.env
  server/package.json
  server/src/config/config.js
  server/src/config/index.js
  server/src/controllers/index.js
  server/src/db/connect.js
  server/src/db/index.js
  server/src/index.js
  server/src/middlewares/index.js
  server/src/models/index.js
  server/src/models/userModel.js
  server/src/routes/index.js
  server/src/server.js
Labels: user-story, feat

#41 F/36 LogIn SignUp nav bar
  client/src/components/SignNav/SignNav.js
  client/src/components/SignNav/index.js
  client/src/pages/Login/Login.js
  client/src/pages/Register/Register.js
  client/src/pages/Register/register.css
Labels: feat

#42 F/39
  client/src/App.js
  client/src/index.css
  client/src/pages/Home/Home.js
Labels: feat

#43 F/38b
  client/public/assets/img/home.svg
  client/public/assets/img/logout.svg
  client/public/assets/img/search.svg
  client/src/App.js
  client/src/colors.css
  client/src/components/ProfileCircleIcon/ProfileCircleIcon.js
  client/src/components/ProfileCircleIcon/index.js
  client/src/components/ProfileCircleIcon/styles.css
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/index.js
  client/src/components/RightMenu/styles.css
  client/src/index.css
  client/src/index.js
Labels: user-story, feat

#44 F/14
  client/src/index.js
  client/src/pages/Profile/Profile.js
Labels: feat

#45 Frontend: Firebase in client side.
  client/package.json
  client/public/assets/img/logout.svg
  client/src/App.js
  client/src/components/RightMenu/RightMenu.js
  client/src/index.js
  client/src/pages/Login/Login.js
  client/src/pages/Register/Register.js
  client/src/services/firebase.js
  client/src/services/firebaseConfig.js
Labels: feat

#46 B/register firebase
  client/package.json
  client/src/pages/Register/Register.js
  server/.env
  server/package.json
  server/src/config/config.js
  server/src/controllers/index.js
  server/src/controllers/userController.js
  server/src/middlewares/authMiddleware.js
  server/src/middlewares/index.js
  server/src/models/userModel.js
  server/src/routes/index.js
  server/src/routes/userRoutes.js
  server/src/server.js
  server/src/services/firebase/firebase.js
Labels: feat

#49 Corrected component Input
  client/src/components/Input/Input.js
  client/src/pages/Login/Login.js
  client/src/pages/Register/Register.js
Labels: feat

#50 F47/redo
  client/public/assets/img/apollofy-music-project-firebase-adminsdk-eub4j-a33eeadcc7.json
  client/src/colors.css
  client/src/components/Button/Button.js
  client/src/components/Button/index.js
  client/src/components/Input/styles.css
  client/src/components/ProfileCircleIcon/ProfileCircleIcon.js
  client/src/components/ProfileCircleIcon/styles.css
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/styles.css
  client/src/components/SignNav/SignNav.js
  client/src/components/SignNav/styles.css
  client/src/index.css
  client/src/pages/Home/Home.js
  client/src/pages/Login/Login.js
  client/src/pages/Login/login.css
  client/src/pages/Profile/Profile.js
  client/src/pages/Register/Register.js
Labels: fix

#51 firstname and lastname added, state changed
  .gitignore
  client/src/pages/Register/Register.js
  client/src/pages/Register/register.css
Labels: user-story, fix

#53 Recovery inputs correction
  .gitignore
  client/src/components/Button/Button.js
  client/src/components/Button/index.js
  client/src/components/Input/Input.js
  client/src/pages/Login/Login.js
  client/src/pages/Register/Register.js
  client/src/pages/Register/register.css
Labels: fix

#54 Corrected inputs again and register inputs
  client/src/components/Input/Input.js
  client/src/pages/Login/Login.js
  client/src/pages/Register/Register.js
Labels: fix

#55 Fb/conexion firebase api
  client/src/App.js
  client/src/pages/Register/Register.js
  client/src/services/api/apiAuth.js
  client/src/services/api/index.js
  client/src/services/firebase.js
  server/src/controllers/userController.js
  server/src/models/userModel.js
Labels: feat, fix

#57 fix: remove defaultValue from Input component
  client/src/components/Input/Input.js
Labels: fix

#58 F/login register input right menu
  client/src/colors.css
  client/src/components/Button/Button.js
  client/src/components/Button/styles.css
  client/src/components/Input/Input.js
  client/src/components/Input/styles.css
  client/src/components/ProfileCircleIcon/styles.css
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/styles.css
  client/src/components/SignNav/SignNav.js
  client/src/components/SignNav/styles.css
  client/src/index.css
  client/src/pages/Login/Login.js
  client/src/pages/Login/login.css
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/styles.css
  client/src/pages/Register/Register.js
  client/src/pages/Register/register.css
Labels: user-story, feat, fix

#59 Password reset implemented with firebase
  client/src/App.js
  client/src/pages/Login/Login.js
  client/src/pages/ResetPassword/ResetPassword.js
  client/src/pages/ResetPassword/index.js
  client/src/pages/ResetPassword/reset-password.css
  client/src/services/firebase.js
Labels: feat

#60 Profile inputs --> done, submit object-->done #15
  client/src/App.js
  client/src/components/Button/Button.js
  client/src/components/RightMenu/RightMenu.js
  client/src/pages/Home/Home.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/styles.css
  client/src/pages/RecoverPassword/RecoverPassword.js
  client/src/pages/RecoverPassword/index.js
  client/src/pages/RecoverPassword/styles.css
  client/src/pages/ResetPassword/index.js
Labels: must-have, user-story, feat

#61 Firebase HOC and Authorization redux component implemented
  client/src/App.js
  client/src/hoc/withAuth.js
  client/src/hoc/withoutAuth.js
  client/src/pages/Home/Home.js
  client/src/pages/Login/Login.js
  client/src/pages/Profile/Profile.js
  client/src/pages/RecoverPassword/RecoverPassword.js
  client/src/pages/Register/Register.js
  client/src/redux/isAuthorized/actions.js
  client/src/redux/isAuthorized/reducer.js
  client/src/redux/isAuthorized/state.js
  client/src/redux/isAuthorized/types.js
  client/src/redux/reducers.js
  client/src/redux/stringTest/action.js
  client/src/redux/stringTest/reducer.js
  client/src/redux/stringTest/state.js
  client/src/redux/stringTest/types.js
Labels: feat

#64 B/52 crud verify token
  client/src/pages/Home/Home.js
  client/src/pages/Login/Login.js
  client/src/pages/Profile/Profile.js
  client/src/pages/RecoverPassword/RecoverPassword.js
  client/src/pages/Register/Register.js
  client/src/redux/userData/action.js
  client/src/redux/userData/reducer.js
  client/src/redux/userData/state.js
  client/src/redux/userData/types.js
  client/src/services/api/apiAuth.js
  client/src/services/api/index.js
  client/src/services/firebase.js
  server/package.json
  server/src/config/config.js
  server/src/controllers/userController.js
  server/src/middlewares/authMiddleware.js
  server/src/routes/userRoutes.js
Labels: feat, fix

#65 Fb/#52 finish update
  client/src/pages/Profile/Profile.js
  client/src/services/api/apiAuth.js
  client/src/services/api/index.js
  client/src/services/firebase.js
  server/src/controllers/userController.js
  server/src/models/userModel.js
  server/src/routes/userRoutes.js
Labels: must-have, feat

#66 #52 fix register -->done
  server/src/controllers/userController.js
Labels: fix

#67 F/responsive login register
  client/src/colors.css
  client/src/components/Input/styles.css
  client/src/components/RightMenu/RightMenu.js
  client/src/index.css
  client/src/pages/Login/Login.js
  client/src/pages/Login/login.css
  client/src/pages/Profile/Profile.js
  client/src/pages/Register/Register.js
  client/src/services/api/apiAuth.js
Labels: user-story, feat, fix

#97 feat: change user password(frontend/backend) --> done
  client/src/components/Button/styles.css
  client/src/components/Input/styles.css
  client/src/pages/Profile/Profile.js
  client/src/services/firebase.js
Labels: must-have, user-story, feat

#102 F/change pass
  client/src/App.js
  client/src/pages/ChangePassword/ChangePassword.js
  client/src/pages/ChangePassword/index.js
  client/src/pages/ChangePassword/styles.css
  client/src/pages/RecoverPassword/RecoverPassword.js
Labels: feat

#104 F/change password 2
  client/src/App.js
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/styles.css
  client/src/index.css
  client/src/pages/ChangePassword/ChangePassword.js
  client/src/pages/Login/Login.js
Labels: fix

#106 B/track schema crud
  server/src/controllers/index.js
  server/src/controllers/trackController.js
  server/src/models/index.js
  server/src/models/trackModel.js
  server/src/models/userModel.js
  server/src/routes/index.js
  server/src/routes/trackRoutes.js
  server/src/server.js
Labels: must-have, feat

#107 B/track schema crud
  server/src/controllers/trackController.js
  server/src/controllers/userController.js
  server/src/index.js
  server/src/models/index.js
Labels: must-have, feat

#108 F/cloudinary
  client/package-lock.json
  client/public/assets/img/upload.svg
  client/src/components/ModalTrackUp/ModalTrackUp.js
  client/src/components/ModalTrackUp/index.js
  client/src/components/ModalTrackUp/styles.css
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/styles.css
  client/src/index.css
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/spinner.css
  client/src/pages/Profile/styles.css
  client/src/pages/RecoverPassword/styles.css
  client/src/services/api/index.js
  client/src/services/api/trackUpload.js
  package-lock.json
  server/package-lock.json
  server/src/models/trackModel.js
Labels: feat

#109 F/#83 reducer de canciones
  client/package.json
  client/src/components/PlayButton/PlayButton.js
  client/src/components/PlayButton/index.js
  client/src/components/RightMenu/RightMenu.js
  client/src/components/Track/Track.js
  client/src/components/Track/index.js
  client/src/components/Track/styles.css
  client/src/index.css
  client/src/pages/Home/Home.js
  client/src/pages/Profile/Profile.js
  client/src/redux/reducers.js
  client/src/redux/trackData/actions.js
  client/src/redux/trackData/reducer.js
  client/src/redux/trackData/state.js
  client/src/redux/trackData/type.js
  client/src/redux/userData/action.js
  client/src/redux/userData/actions.js
  client/src/redux/userData/reducer.js
  client/src/redux/userData/state.js
  client/src/redux/userData/types.js
Labels: must-have, feat

#110 B/endpoint like track handler
  server/src/controllers/trackController.js
  server/src/index.js
  server/src/models/trackModel.js
  server/src/models/userModel.js
  server/src/routes/trackRoutes.js
Labels: feat

#111 #83 totalPlays increment handle --> done
  server/src/controllers/trackController.js
  server/src/routes/trackRoutes.js
Labels: feat

#112 F/cloudinary
  client/public/assets/img/uploaded.svg
  client/src/colors.css
  client/src/components/ModalTrackUp/ModalTrackUp.js
  client/src/components/ModalTrackUp/styles.css
  client/src/components/RightMenu/RightMenu.js
  client/src/components/RightMenu/styles.css
  client/src/hoc/BarsAndModal.js
  client/src/pages/Home/Home.js
  client/src/pages/Profile/Profile.js
  client/src/pages/Profile/styles.css
  client/src/services/api/index.js
  client/src/services/api/trackUpload.js
Labels: must-have, user-story, feat
